if ( GetLocale() == "zhTW" ) then

LC_ROTATION_TPS = "TPS：技能循环";
LC_ROTATION_TPS_DESCRIPTION = "设置每秒技能循环的响应次数";
LC_UNITS_TPS = "TPS：单位扫描";
LC_UNITS_TPS_DESCRIPTION = "设置每秒对附近单位的分析次数";
LC_DEFALUT_VALUE = "默认值";

-- RotationOptions Common
LC_ARCANE_TORRENT = "奥术洪流"
LC_ARCANE_TORRENT_DESCRIPTION = "|cffFFBB00自动使用奥术洪流"
LC_ARTIFACT = "神器"
LC_ARTIFACT_CD = "大技能"
LC_ARTIFACT_EVERY_TIME = "任何时候"
LC_AUTO_FACING = "自动面向目标"
LC_AUTO_FACING_DESCRIPTION = "自动面向目标";
LC_AUTO_TARGET = "自动选择目标";
LC_AUTO_TARGET_DESCRIPTION = "自动选择目标";
LC_BERSERKING = "嗜血术";
LC_BERSERKING_DESCRIPTION = "|cffFFBB00自动使用嗜血术";
LC_BLOOD_FURY = "血之狂怒";
LC_BLOOD_FURY_DESCRIPTION = "|cffFFBB00自动使用血之狂怒";
LC_COOLDOWNS = "大技能";
LC_DEADLY_GRACE = "|cffFFFF00致命优雅";
LC_DEFENSIVE = "自保";
LC_DOT_MINIMUM_HEALTH = "Dot最小血量";
LC_DOT_MINIMUM_HEALTH_DESCRIPTION = "|cffFFBB00多线输出下Dot施放最小血量（百万）";
LC_FLASK = "合剂";
LC_GENERAL = "常规";
LC_GIFT_OF_THE_NAARU = "纳鲁的礼物";
LC_GIFT_OF_THE_NAARU_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_INTERRUPTS = "打断";
LC_INTERRUPTS_AT = "打断位置";
LC_INTERRUPTS_AT_DESCRIPTION = "|cffFFFFFF在施法百分比打断，0为随机百分比";
LC_OLD_WAR = "|cffFFFF00上古战神";
LC_POT_STONED = "药水/糖";
LC_POT_STONED_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_POTION = "爆发药水";
LC_PRE_PULL_BOSSMOD = "BOSS开怪前准备";
LC_PRE_PULL_TIMER = "开怪倒计时";
LC_PRE_PULL_TIMER_DESCRIPTION =  "|cffFFFFFF在开怪倒计时到达多少秒时进行准备（需要DBM）";
LC_PROLONGED_POWER = "|cff00BB00延时之力";
LC_RACIAL = "种族技能";
LC_WAR_STOMP = "战争践踏";
LC_TRINKETS = "饰品";
LC_TRINKETS_DESCRIPTION = "自动使用饰品";
LC_TRINKETS1_DURATION = "饰品1持续时间";
LC_TRINKETS2_DURATION = "饰品2持续时间";
LC_APL = "APL";
LC_APL_710 = "7.10";
LC_APL_715 = "7.15";
LC_ENEMIES_FOR_AOE = "AOE敌人数量";

-- Priest
LC_BODY_AND_SOUL = "身心合一";
LC_BODY_AND_SOUL_DESCRIPTION = "|cffFFBB00在玩家移动时，延时n秒使用|cffFF0000真言术：盾|cffFFBB00来触发身心合一。S2M时无效";

-- Shawdow Priest
LC_BLESSED_DAWNLIGHT_MEDALLION = "使用项链"
LC_BLESSED_DAWNLIGHT_MEDALLION_DESCRIPTION = "|cffFFBB00在开启自杀后下一个GCD将会死亡前自动使用项链"
LC_DISPERSION = "影散"
LC_DISPERSION_DESCRIPTION = "|cffFFBB00让系统自动判断使用影散的时机"
LC_EXECUTE_ACTORS = "带斩杀队友数";
LC_EXECUTE_ACTORS_DESCRIPTION = "带斩杀队友数（包括自己）";
LC_MINDBENDER_SHADOWFIEND = "摧心魔/暗影魔"
LC_POWER_INFUSION = "能量灌注"
LC_S2M_CHECK = "预估自杀秒数";
LC_S2M_CHECK_DESCRIPTION = "预估自杀的可持续秒数";
LC_SWP_MAX_TARGETS = "多目标 暗言术：痛";
LC_SWP_MAX_TARGETS_DESCRIPTION = "|cffFFBB00暗言术：痛 目标上限";
LC_TIME_TO_USE_POWER_INFUSION = "开启能量灌注的时机"
LC_TIME_TO_USE_POWER_INFUSION_DESCRIPTION = "|cffFFBB00开启能量灌注的时机，以秒为单位，并不一定等于当前层数"
LC_VAMPIRIC_EMBRACE = "吸血鬼的拥抱";
LC_VAMPIRIC_EMBRACE_DESCRIPTION = "|cffFFBB00当血量低于设定百分比时使用|cffFF0000吸血鬼的拥抱";
LC_VT_MAX_TARGETS = "多目标 吸血之触";
LC_VT_MAX_TARGETS_DESCRIPTION = "|cffFFBB00吸血之触 目标上限";

-- DeathKnight
LC_DARK_SUCCOR = "黑暗救赎";
LC_DARK_SUCCOR_DESCRIPTION = "|cffFFBB00当HP少于设定值时，使用黑暗救赎触发的免费|cffFF0000死亡打击";
LC_DEATH_STRIKE = "死亡打击";
LC_DEATH_STRIKE_DESCRIPTION = "|cffFFBB00当HP少于设定值时，使用|cffFF0000死亡打击";
LC_ICEBOUND_FORTITUDE = "冰锢坚韧"; 
LC_ICEBOUND_FORTITUDE_DESCRIPTION = "|cffFFBB00当HP少于设定值时，使用|cffFF0000冰锢坚韧";
LC_MIND_FREEZE = "心智冰封";
LC_MIND_FREEZE_DESCRIPTION = "心智冰封";

-- Frost DeathKnight
LC_BLINDING_SLEET = "致盲冻雨"
LC_BLINDING_SLEET_DESCRIPTION = "致盲冻雨"
LC_BLINDING_SLEET_HP = "致盲冻雨 - HP"
LC_BLINDING_SLEET_HP_DESCRIPTION = "|cffFFBB00当HP少于设定值时，使用|cffFF0000致盲冻雨"
LC_BREATH_OF_SINDRAGOSA = "辛德拉苟萨之息"
LC_BREATH_OF_SINDRAGOSA_DESCRIPTION = "自动使用辛德拉苟萨之息"
LC_CHAINS_OF_ICE = "冰链术";
LC_CHAINS_OF_ICE_DESCRIPTION = "自动使用冰链术";
LC_HORN_OF_WINTER = "凛冬号角";
LC_HORN_OF_WINTER_DESCRIPTION = "自动使用凛冬号角";
LC_OBLITERATION = "灭体抹杀";
LC_OBLITERATION_DESCRIPTION = "自动使用灭体抹杀";
LC_PILLAR_OF_FROST = "冰霜之柱";
LC_PILLAR_OF_FROST_DESCRIPTION = "自动使用冰霜之柱";
LC_RUNE_WEAPON = "强力/饥饿符文武器"
LC_RUNE_WEAPON_DESCRIPTION = "自动使用强力/饥饿符文武器"

-- Paladin
LC_BLESSING_OF_PROTECTION = "保护祝福";
LC_BLESSING_OF_PROTECTION_DESCRIPTION = "|cffFFFFFF团队中有队员血量低于设定百分比时使用";
LC_BLINDING_LIGHT = "盲目之光";
LC_BLINDING_LIGHT_AOE = "盲目之光 - AoE";
LC_BLINDING_LIGHT_AOE_DESCRIPTION = "|cffFFFFFF当10码范围内有多少目标时使用";
LC_BLINDING_LIGHT_DESCRIPTION = "|cffFFFFFF使用盲目之光打断施法";
LC_BLINDING_LIGHT_HP = "盲目之光 - 自保";
LC_BLINDING_LIGHT_HP_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_DIVINE_SHIELD = "圣盾术";
LC_DIVINE_SHIELD_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_FLASH_OF_LIGHT = "圣光闪现";
LC_FLASH_OF_LIGHT_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_HAMMER_OF_JUSTICE = "制裁之锤";
LC_HAMMER_OF_JUSTICE_DESCRIPTION = "|cffFFFFFF使用制裁之锤打断施法";
LC_HAMMER_OF_JUSTICE_HP = "制裁之锤 - 自保";
LC_HAMMER_OF_JUSTICE_HP_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_REBUKE = "责难";
LC_REBUKE_DESCRIPTION = "|cffFFFFFF使用责难打断施法";
LC_REDEMPTION = "救赎";
LC_REDEMPTION_DESCRIPTION = "对死亡的目标使用救赎";

-- Retribution Paladin
LC_AVENGING_WRATH_CRUSADE = "复仇之怒/十字军";
LC_AVENGING_WRATH_CRUSADE_DESCRIPTION = "|cffFFFFFF自动使用复仇之怒/十字军";
LC_EXCUTION_SENTENCE = "处决宣判";
LC_EXCUTION_SENTENCE_DESCRIPTION = "|cffFFFFFF自动使用处决宣判";
LC_EYE_FOR_AN_EYE = "以眼还眼";
LC_EYE_FOR_AN_EYE_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_GREATER_BLESSING = "强效祝福";
LC_GREATER_BLESSING_DESCRIPTION = "单人时，对自己使用强效祝福";
LC_HOLY_WRATH = "神圣愤怒";
LC_HOLY_WRATH_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_JUDGMENT_IGNORE = "无视审判";
LC_JUDGMENT_IGNORE_DESCRIPTION = "|cffFFFFFF当审判CD过长时，无视目标审判的debuff，打循环";

-- Demonology Warlock
LC_COOLDOWN_DOOMGUARD = "末日守卫 ";
LC_COOLDOWN_INFERNAL = "地狱火 ";
LC_DARK_PACT = "黑暗契约";
LC_DARK_PACT_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_DRAIN_LIFE = "吸取生命";
LC_DRAIN_LIFE_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_GRIMOIRE_OF_SERVICE = "服侍宝典";
LC_GRIMOIRE_OF_SERVICE_DESCRIPTION = "|cffFFFFFF选择恶魔";
LC_GRIMOIRE_OF_SERVICE_FELGUARD = "恶魔守卫";
LC_GRIMOIRE_OF_SERVICE_FELHUNTER = "恶魔猎犬";
LC_GRIMOIRE_OF_SERVICE_IMP = "小鬼";
LC_GRIMOIRE_OF_SERVICE_SUCCUBUS = "魅魔";
LC_GRIMOIRE_OF_SERVICE_VOIDWALKER = "虚空行者";
LC_GRIMOIRE_OF_SUPREMACY = "统御宝典";
LC_GRIMOIRE_OF_SUPREMACY_DESCRIPTION = "|cffFFFFFF选择恶魔";
LC_GRIMOIRE_OF_SUPREMACY_DOOMGUARD = "末日守卫";
LC_GRIMOIRE_OF_SUPREMACY_INFERNAL = "地狱火";
LC_HEALTH_FUNNEL = "生命通道";
LC_HEALTH_FUNNEL_DESCRIPTION = "|cffFFFFFF宠物血量低于设定百分比时使用";
LC_SHADOW_LOCK = "暗影枷锁";
LC_SOUL_HARVEST = "灵魂收割";
LC_SOUL_HARVEST_DESCRIPTION = "|cffFFFFFF灵魂收割";
LC_SOULSTONE = "灵魂石";
LC_SPELL_LOCK = "法术封锁";
LC_SUMMON_PET = "召唤恶魔";
LC_SUMMON_PET_AUTO = "自动";
LC_SUMMON_PET_DESCRIPTION = "|cffFFFFFF选择召唤恶魔的类型";
LC_SUMMON_PET_FELGUARD = "恶魔守卫";
LC_SUMMON_PET_FELHUNTER = "恶魔猎犬";
LC_SUMMON_PET_IMP = "小鬼";
LC_SUMMON_PET_SUCCUBUS = "魅魔";
LC_SUMMON_PET_VOIDWALKER = "虚空行者";
LC_UNENDING_RESOLVE = "心志坚定";
LC_UNENDING_RESOLVE_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";

-- Destruction Warlock
LC_HAVOC = "浩劫";
LC_HAVOC_DESCRIPTION = "敌人血量高于设定值时，施放浩劫（百万）";
LC_CATACLYSM = "灾变";
LC_CATACLYSM_DESCRIPTION = "|cffFFFFFF灾变";

-- Affliction Warlock
LC_AGONY_TARGETS = "痛苦最大目标数";
LC_AGONY_TARGETS_HP = "痛苦目标最低血量(百万)";
LC_AGONY_TARGETS_TTD = "痛苦目标死亡倒计时不低于(秒)";
LC_CORRUPTION_TARGETS = "腐蚀术最大目标数";
LC_CORRUPTION_TARGETS_HP = "腐蚀术目标最低血量(百万)";
LC_CORRUPTION_TARGETS_TTD = "腐蚀术目标死亡倒计时不低于(秒)";
LC_SIPHON_LIFE_TARGETS = "生命虹吸最大目标数";
LC_SIPHON_LIFE_TARGETS_HP = "生命虹吸目标最低血量(百万)";
LC_SIPHON_LIFE_TARGETS_TTD = "生命虹吸目标死亡倒计时不低于(秒)";
LC_REAP_SOULS = "收割灵魂";
LC_REAP_SOULS_DESCRIPTION = "|cffFFFFFF多少个灵魂的时候启动神器技能，当选择|cffFFBB00恶毒之握|cffFFFFFF天赋时，始终为1";
LC_SOC_MODE_ENABLE = "开启低血量ADD击杀模式，提高腐蚀之种优先级";
LC_SOC_MODE_DISABLE = "闭关低血量ADD击杀模式";

-- Shaman
LC_ANCESTRAL_SPIRIT = "先祖之魂";
LC_ASTRAL_SHIFT = "星界转移";
LC_ASTRAL_SHIFT_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";
LC_HEALING_SURGE = "汹涌治疗";
LC_HEALING_SURGE_DESCRIPTION = "|cffFFFFFF血量低于设定百分比时使用";

-- Enhancement Shaman
LC_FERAL_LUNGE = "野性突袭";
LC_FERAL_SPIRIT = "野性狼魂";
LC_GHOST_WOLF = "鬼魂之狼";
LC_GHOST_WOLF_DESCRIPTION = "鬼魂之狼延迟(s)";
LC_WATER_WALKING = "水上行走";
LC_WIND_SHEAR = "削风术";
LC_DOOM_WINDS_DELAY = "末日之风延迟";
LC_DOOM_WINDS_DELAY_DESCRIPTION = "末日之风等待疾风打击最大时间";

-- Elemental Shaman
LC_ASCENDANCE = "卓越术";
LC_ASCENDANCE_DESCRIPTION = "|cffFFFFFF卓越术";
LC_ELEMENTAL_MASTERY = "精通元素";
LC_ELEMENTAL_MASTERY_DESCRIPTION = "|cffFFFFFF精通元素";
LC_FIRE_ELEMENTAL = "火元素";
LC_FIRE_ELEMENTAL_DESCRIPTION = "|cffFFFFFF火元素";

-- Assassination Rogue
LC_STEALTH = "潜行";
LC_STEALTH_ALWAYS = "|cffFFBB00总是";
LC_STEALTH_HAS_TARGET = "|cffFF0000有目标时";
LC_POISON = "毒药";
LC_MARKED_FOR_DEATH = "死亡标记";
LC_VENDETTA = "宿怨";
LC_VANISH = "消失";
LC_EXSANGUINATE = "放血";
LC_CRIMSON_VIAL = "赤红药瓶";
LC_EVASION = "闪避";

-- Outlaw Rogue
LC_KICK = "脚踢";
LC_BLIND = "致盲";
LC_GOUGE = "凿击";

-- Havoc Demon Hunter
LC_LOW_FURY = "怒气过低 - 收集灵魂碎片！";
LC_ENEMIES_FOR_AOE_HDH = "|cffFF0000AOE敌人数量，影响|cffFFBB00眼棱，邪能弹幕，伊利达雷之怒";
LC_CONSUME_MAGIC = "吞噬魔法";
LC_CHAOS_NOVA = "混沌新星";

end